{{
  config(
    materialized='incremental',
    on_schema_change="append_new_columns"
    )
}}

with WRK as (
  select * from {{ ref('TB_WRK_EXTRATO_TAS__VALIDA_FATURA_ROUTER') }}
),

FILTERED as (
  select
    OUT_CYCLE_DATE,
    CONTA_CONTA,
    BILLING_DATE_INI,
    BILLING_DATE_FIM,
    CONTA_TOTAL_CREDITS,
    CONTA_TOTAL_DEBITS,
    CONTA_MINDUEAMOUNT,
    CONTA_TOTAL_PAYMETNS,
    CONTA_OPENING_BALANCE,
    CONTA_CLOSING_BALANCE,
    CONTA_INSTALMENT_AMT,
    DT_CARGA,
    SERNO_ODS
  from WRK
  where route_group = 'CONTA_NAO_CADASTRO_ODS'
)

select
  out_cycle_date as CYCLE_DATE,
  CONTA_CONTA,
  BILLING_DATE_INI,
  BILLING_DATE_FIM,
  CONTA_TOTAL_CREDITS,
  CONTA_TOTAL_DEBITS,
  CONTA_MINDUEAMOUNT,
  CONTA_TOTAL_PAYMETNS,
  CONTA_OPENING_BALANCE,
  CONTA_CLOSING_BALANCE,
  CONTA_INSTALMENT_AMT,
  DT_CARGA,
  serno_ods as SERNO_ODS
from FILTERED

