version: 2

sources:
  - name: TESSERA_TRUSTED_EXTRATO_TAS
    database: |
      {%- if  target.name == "prd" -%} {{ var("tessera")["prd"] }}
      {%- elif target.name == "hml" -%} {{ var("tessera")["hml"] }}
      {%- else -%} {{ var("tessera")["crt"]  }}
      {%- endif -%}
    schema: trusted
    description: Dataset trusted
    meta:
      owner: "@analytics_engineer"
    tables:
      - name: tsys_issuerstatement_conta
      - name: tsys_issuerstatement_transacoes
      - name: tsys_issuerstatement_cliente
      - name: tsys_issuerstatement_codigo_barra